# SCREEN  SETTINGS
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60 
LINE_WIDTH = 3
BRIGHTNESS_BACKGROUND = 30 # 1 - 100
FONT_SIZE = 40
ACHTERGROND = "melkweg.jpg" 
DEATH_SCREEN = "deathscreen.jpg"

# PLAYER SETTINGS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 130
BOOST_AMP = 1.5

# SCHOOTING SETTINGS
SHOT_RADIUS = 5
SHOT_SPEED = 500        
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.1

# ASTEROID SETTINGS
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SPLITTED_ASTEROID_VELOCITY_MULTIPLIER = 1.5

# RARE ASTEROID SETTINGS
ASTEROID_RARE_RADIUS = 5
ASTEROID_RARE_SPAWN_RATE = 10
ASTEROID_RARE_POINTS = 200
ASTEROID_RARE_SPEED = 175

# COLOR SETTINGS
COLOR_PLAYER = "yellow"
COLOR_ASTROIDS = "purple"
COLOR_SHOTS = "blue"
COLOR_SCORE = "white"
COLOR_ASTEROID_RARE = "gold"
COLOR_DIED_TEXT = "white"

