SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60     # Bepaald FPS maar ook snelheid. 2X hogere fps is 2x zo snel en 2x alles 
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 5
SHOT_SPEED = 500        
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
SPLITTED_ASTEROID_VELOCITY_MULTIPLIER = 1.5

COLOR_PLAYER = "red"
COLOR_ASTROIDS = "white"
COLOR_SHOTS = "purple"


# ASTEROID_MIN_RADIUS = 20
# ASTEROID_KINDS = 3
# ASTEROID_SPAWN_RATE_SECONDS = 0.8 300
# ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS