# SCREEN  SETTINGS
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60 
LINE_WIDTH = 3
BRIGHTNESS_BACKGROUND = 55 # 1 - 100
FONT_SIZE = 40
ACHTERGROND = "melkweg.jpg" 
DEATH_SCREEN = "deathscreen.jpg"

# GAME SETTINGS
SCORE_FOR_FASE_UP = 300
AMMOUNT_OF_FASES = 4
POINTS_SMALL_ASTEROID = 3
POINTS_MEDIUM_ASTEROID = 5
POINTS_LARGE_ASTEROID = 10
ASTEROID_RARE_POINTS = 200
FASE_SPAWNRATE_SPEED_AMP = 1.3
TELEPORT_COOLDOWN = 5

# PLAYER SETTINGS
PLAYER_RADIUS = 15
PLAYER_TURN_SPEED = 250
PLAYER_SPEED = 130
BOOST_AMP = 1.5

# SCHOOTING SETTINGS
SHOT_RADIUS = 5
SHOT_SPEED = 1000     
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.15
LARGE_SHOT_RADIUS = 20

# ASTEROID SETTINGS
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 3
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SPLITTED_ASTEROID_VELOCITY_MULTIPLIER = 1.5

# RARE ASTEROID SETTINGS
ASTEROID_RARE_RADIUS = 5
ASTEROID_RARE_SPAWN_RATE = 10
ASTEROID_RARE_SPEED = 250

# SUPER SHOT
SUPER_SHOT_RADIUS = 20
SUPER_SHOT_SPEED = 1500
SUPER_SHOT_TIMER = 5

# COLOR SETTINGS
COLOR_PLAYER = "red"
COLOR_ASTROIDS = "white"
COLOR_SHOTS = "grey"
COLOR_SCORE = "white"
COLOR_ASTEROID_RARE = "gold"
COLOR_DIED_TEXT = "white"
COLOR_FASE = "white"
COLOR_FPS = "white"
COLOR_SUPER_SHOT = "yellow"

# KEYBINDS (Must be pygame's key names)
FORWARD = "UP"
LEFT = "LEFT"
RIGHT = "RIGHT"
BACKWARDS = "DOWN"
SHOOT = "SPACE"
SUPER_SHOOT = "E"
BOOST = "left shift"
TELEPORT = "R"
